### PR TITLE
feat: use spec-node

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by fsoikin** [comment]
Awesome, thank you very much @srghma!

Could you please add a summary in `CHANGELOG.md` under "unreleased"?

**Comment by srghma** [comment]
@fsoikin Added

**Review by fsoikin — APPROVED** [review]

**Comment by fsoikin** [comment]
Published [v8.4.0](https://github.com/purescript-spec/purescript-spec-discovery/releases/tag/v8.4.0)

**Comment by srghma** [comment]
Awesome!

If You want, You could add me to the org

I will still be making prs and seek approval, just maybe ... cannot find a reason

**Pull request merged**
