### PR TITLE
[fix]Discovery on Windows using file:// URL

### PR DESCRIPTION
**Pull request by CarstenKoenig**
this should fix Issue #30 on Windows without changing behavior on other OSs

### CODE REVIEW

**Comment by CarstenKoenig** [comment]
I just noticed, that my editor (VS code) did choose to reformat the whole file on save (including changes to `"` -> `'` etc.).
Please let me know if this is a problem - if so I'll redo

**Comment by i-am-the-slime** [comment]
Thanks!

**Comment by CarstenKoenig** [comment]
Hi,

first thanks for merging the code - I'm glad I could be of help.

Is there any chance that you could release a new version including the changes?
It's no big deal to change the .dhall files to point to this commit but  I'd rather have the unchanged sources in my projects.

**Comment by i-am-the-slime** [comment]
@CarstenKoenig 
I released v0.8.1. Feel free to update the package set.

**Pull request merged**
